// Generated by https://quicktype.io

namespace NpcGen
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Races
    {
        [JsonProperty("index")]
        public string Index { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("speed")]
        public int Speed { get; set; }

        [JsonProperty("ability_bonuses")]
        public AbilityBonus[] AbilityBonuses { get; set; }

        [JsonProperty("ability_bonus_options")]
        public AbilityBonusOptions AbilityBonusOptions { get; set; }

        [JsonProperty("alignment")]
        public string Alignment { get; set; }

        [JsonProperty("age")]
        public string Age { get; set; }

        [JsonProperty("size")]
        public string Size { get; set; }

        [JsonProperty("size_description")]
        public string SizeDescription { get; set; }

        [JsonProperty("starting_proficiencies")]
        public Language[] StartingProficiencies { get; set; }

        [JsonProperty("starting_proficiency_options")]
        public Options StartingProficiencyOptions { get; set; }

        [JsonProperty("languages")]
        public Language[] Languages { get; set; }

        [JsonProperty("language_options")]
        public Options LanguageOptions { get; set; }

        [JsonProperty("language_desc")]
        public string LanguageDesc { get; set; }

        [JsonProperty("traits")]
        public Language[] Traits { get; set; }

        [JsonProperty("subraces")]
        public Language[] Subraces { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("trait_options", NullValueHandling = NullValueHandling.Ignore)]
        public Options TraitOptions { get; set; }
    }

    public partial class AbilityBonusOptions
    {
        [JsonProperty("choose", NullValueHandling = NullValueHandling.Ignore)]
        public int? Choose { get; set; }

        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public string Type { get; set; }

        [JsonProperty("from", NullValueHandling = NullValueHandling.Ignore)]
        public AbilityBonus[] From { get; set; }
    }

    public partial class AbilityBonus
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("bonus")]
        public int Bonus { get; set; }
    }

    public partial class Options
    {
        [JsonProperty("choose", NullValueHandling = NullValueHandling.Ignore)]
        public int? Choose { get; set; }

        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public string Type { get; set; }

        [JsonProperty("from", NullValueHandling = NullValueHandling.Ignore)]
        public Language[] From { get; set; }
    }

    public partial class Language
    {
        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

    public partial class Races
    {
        public static Races[] FromJson(string json) => JsonConvert.DeserializeObject<Races[]>(json, NpcGen.Converter.Settings);
    }
}
